### ISSUE TITLE
问题求助 无法正常运行

### ISSUE THREAD

**Issue by SmartYou1995** [b3nguang/DingTalkLiveDownload#1]
win11 已下载chrome     go.exe  
运行时./DingTalkLiveDownload_darwin_arm64 
一直提示选择用什么应用打开

**Comment by b3nguang** [comment]
您试试运行 ./DingTalkLiveDownload_windows_amd64.exe 试试看？

**Comment by SmartYou1995** [comment]
> 您试试运行 ./DingTalkLiveDownload_windows_amd64.exe 试试看？

可以啦~  但是下载的片段不合并是吧

**Comment by b3nguang** [comment]
能截图看一下结果吗，应该是下载ts文件再用ffmpeg合并到一起的

**Comment by b3nguang** [comment]
> > 您试试运行 ./DingTalkLiveDownload_windows_amd64.exe 试试看？
> 
> 可以啦~ 但是下载的片段不合并是吧


能截图看一下结果吗，应该是下载ts文件再用ffmpeg合并到一起的

**Comment by SmartYou1995** [comment]
> > > 您试试运行 ./DingTalkLiveDownload_windows_amd64.exe 试试看？
> > 
> > 
> > 可以啦~ 但是下载的片段不合并是吧
> 
> 能截图看一下结果吗，应该是下载ts文件再用ffmpeg合并到一起的

![Uploading 屏幕截图 2024-07-20 101750.png…]()

**Comment by SmartYou1995** [comment]
![屏幕截图 2024-07-20 101750](https://github.com/user-attachments/assets/0141d54f-dcdb-427d-bad4-ef288969a9ce)

**Comment by SmartYou1995** [comment]
> > > 您试试运行 ./DingTalkLiveDownload_windows_amd64.exe 试试看？
> > 
> > 
> > 可以啦~ 但是下载的片段不合并是吧
> 
> 能截图看一下结果吗，应该是下载ts文件再用ffmpeg合并到一起的

![屏幕截图 2024-07-20 101750](https://github.com/user-attachments/assets/cd95fd05-3386-4e11-ad5c-d55017b6a9a1)
存在这样的问题呢  下载完就不进行合并了
